const fs = require('fs');
const path = require('path');
const ComponentLibrary = require('../models/ComponentLibrary');

class ScaffolderEngine {
  constructor() {}

  // Helper to sanitize component types (e.g. Contact-form -> Contactform)
  _sanitizeType(type) {
    return type.replace(/-/g, '');
  }

  async generateSiteCode(design, projectPath) {
    console.log(`[Scaffolder] Generating dynamic code for ${design.projectName}...`);

    this._ensureDirectories(projectPath);

    // 1. Fetch all required components from DB
    const componentTypes = new Set(['Navbar']); // Always include Navbar just in case
    if (design.pages.length > 1) {
      componentTypes.add('Pagination'); // Add Pagination if needed
    }
    
    design.pages.forEach(page => {
      page.components.forEach(comp => {
        componentTypes.add(comp.type);
      });
    });

    const components = await ComponentLibrary.find({ 
      type: { $in: Array.from(componentTypes) },
      $or: [
        { scope: 'GLOBAL' },
        { scope: 'PROJECT', projectName: design.projectName }
      ]
    });

    // Strategy: Project components override global ones if types match
    const componentMap = new Map();
    components.forEach(c => {
      const sType = this._sanitizeType(c.type);
      if (!componentMap.has(sType) || c.scope === 'PROJECT') {
        componentMap.set(sType, c.code);
      }
    });

    // 2. Generate Components from DB templates (with placeholders for missing ones)
    this._generateGlobalComponents(componentMap, projectPath, componentTypes);

    // 3. Generate Static Pages
    await this._generatePages(design, projectPath);

    // 4. Generate Layout & Styles
    this._generateLayout(design, projectPath);
    this._generateGlobalsCss(design, projectPath);

    console.log(`[Scaffolder] Dynamic generation complete.`);
  }

  _ensureDirectories(projectPath) {
    const dirs = [
      path.join(projectPath, 'src', 'components'),
      path.join(projectPath, 'src', 'app'),
      path.join(projectPath, 'src', 'lib')
    ];
    dirs.forEach((dir) => {
      if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    });
  }

  _generateGlobalComponents(componentMap, projectPath, componentTypes) {
    const componentsDir = path.join(projectPath, 'src', 'components');
    
    // Track what we actually created files for
    const finalComponentMap = new Map();

    // 1. Generate files for components found in DB
    for (const [type, code] of componentMap.entries()) {
      fs.writeFileSync(path.join(componentsDir, type + '.tsx'), code);
      finalComponentMap.set(type, true);
    }

    // 2. Generate placeholders for missing types (CRITICAL: Prevents Build Failures)
    componentTypes.forEach(type => {
      const sType = this._sanitizeType(type);
      if (!finalComponentMap.has(sType)) {
        console.warn(`[Scaffolder] Component "${type}" not found in DB. Creating placeholder...`);
        const placeholderCode = `
import React from 'react';

const ${sType}: React.FC<any> = (props) => (
  <div style={{ 
    padding: '40px', 
    border: '2px dashed #f87171', 
    backgroundColor: '#fee2e2', 
    color: '#991b1b',
    textAlign: 'center',
    borderRadius: '8px',
    margin: '10px'
  }}>
    <h3 style={{ margin: '0' }}>Missing Component: <strong>${type}</strong></h3>
    <p style={{ margin: '8px 0 0', opacity: 0.7, fontSize: '14px' }}>
      Please add this component template in the SuperAdmin.
    </p>
    <pre style={{ fontSize: '10px', marginTop: '10px', opacity: 0.5 }}>
      {JSON.stringify(props, null, 2)}
    </pre>
  </div>
);

export default ${sType};
`.trim();
        fs.writeFileSync(path.join(componentsDir, sType + '.tsx'), placeholderCode);
        finalComponentMap.set(sType, true);
      }
    });

    this._generateComponentsIndex(finalComponentMap, projectPath);
  }

  _generateComponentsIndex(componentMap, projectPath) {
    const indexPath = path.join(projectPath, 'src', 'components', 'index.ts');
    let content = '// This file is auto-generated by the CMS Scaffolder\n';
    
    if (componentMap.size > 0) {
      componentMap.forEach((_, type) => {
        const sType = this._sanitizeType(type);
        content += `export { default as ${sType} } from './${sType}';\n`;
      });
    } else {
      content += '// No components found in database for this site generation.\n';
    }
    
    content += '\nexport {}; // Ensure module has at least one export\n';
    fs.writeFileSync(indexPath, content);
  }

  async _generatePages(design, projectPath) {
    const { pages } = design;
    
    for (const page of pages) {
      let routeDir = path.join(projectPath, 'src', 'app');
      if (page.route && page.route !== '/') {
        const subRoute = page.route.startsWith('/') ? page.route.slice(1) : page.route;
        routeDir = path.join(routeDir, subRoute);
      }
      if (!fs.existsSync(routeDir)) fs.mkdirSync(routeDir, { recursive: true });

      // 1. Sort components by order (CRITICAL: README Rule 1)
      const sortedComponents = [...page.components].sort((a, b) => (a.order || 0) - (b.order || 0));
      
      // 2. Enrich component props (CRITICAL: README Rules 2, 3, 5)
      const enrichedComponents = sortedComponents.map(comp => {
        // Rule 5: Preserve ALL props (no data loss)
        const props = comp.props ? JSON.parse(JSON.stringify(comp.props)) : {};
        const safeType = this._sanitizeType(comp.type);
        
        // Rule 3: Add page navigation to header
        if (safeType === 'Header') {
          props.pages = pages.map(p => ({ route: p.route, title: p.title }));
          props.currentRoute = page.route;
        }
        
        // Rule 2 & Background Video Implementation Section: Pass background video to Home
        if (safeType === 'Home' && page.backgroundVideo) {
          props.backgroundVideo = page.backgroundVideo;
        }
        
        return { type: safeType, props };
      });
      
      // 3. Auto-add pagination if multiple pages (CRITICAL: README Rule 4)
      if (pages.length > 1) {
        enrichedComponents.push({
          type: 'Pagination',
          props: {
            pages: pages.map(p => ({ route: p.route, title: p.title })),
            currentRoute: page.route
          }
        });
      }
      
      // 4. Generate page file with background layer logic
      let componentsBlock = enrichedComponents.map(comp => {
        return `<Components.${comp.type} {...${JSON.stringify(comp.props)}} />`;
      }).join('\n              ');

      let bgVideoBlock = '';
      if (page.backgroundVideo) {
         // README: YouTube vs Direct files handling
         const isYouTube = page.backgroundVideo.includes('youtube') || page.backgroundVideo.includes('youtu.be');
         if (isYouTube) {
           bgVideoBlock = `
            <div className="absolute inset-0 z-0">
              <div className="absolute inset-0 bg-black/40 z-10" />
              <iframe
                src={\`https://www.youtube.com/embed/\${${JSON.stringify(page.backgroundVideo)}.match(/(?:youtu\\\\.be\\\\/|v\\\\/|u\\\\/\\\\w\\\\/|embed\\\\/|watch\\\\?v=|\\\\&v=)([^#\\\\&\\\\?]*)/)?.[1]}?autoplay=1&mute=1&loop=1&controls=0&playlist=\${${JSON.stringify(page.backgroundVideo)}.match(/(?:youtu\\\\.be\\\\/|v\\\\/|u\\\\/\\\\w\\\\/|embed\\\\/|watch\\\\?v=|\\\\&v=)([^#\\\\&\\\\?]*)/)?.[1]}&start=0&enablejsapi=0&rel=0&modestbranding=1&playsinline=1\`}
                className="absolute top-1/2 left-1/2 w-[100vw] h-[100vh] -translate-x-1/2 -translate-y-1/2 scale-125"
                style={{ pointerEvents: 'none', minWidth: '100%', minHeight: '100%' }}
                allow="autoplay; encrypted-media"
                frameBorder="0"
              />
            </div>
           `.trim();
         } else {
           bgVideoBlock = `
            <div className="absolute inset-0 z-0">
              <div className="absolute inset-0 bg-black/40 z-10" />
              <video src={${JSON.stringify(page.backgroundVideo)}} autoPlay muted loop playsInline className="absolute top-1/2 left-1/2 w-full h-full -translate-x-1/2 -translate-y-1/2 object-cover" style={{ minWidth: '100%', minHeight: '100%' }} />
            </div>
           `.trim();
         }
      }

      const styleBlock = page.backgroundImage 
        ? `{ backgroundImage: \`url(${page.backgroundImage})\`, backgroundSize: 'cover' }`
        : `{}`;

      const pageContent = `
import * as Components from '@/components';

export default function Page() {
  return (
    <div className="relative min-h-screen" style={${styleBlock}}>
      ${bgVideoBlock}
      <div className="relative z-10 w-full h-full">
        ${componentsBlock}
      </div>
    </div>
  )
}
`.trim();
      
      fs.writeFileSync(path.join(routeDir, 'page.tsx'), pageContent);
    }
  }

  _generateLayout(design, projectPath) {
    const layoutPath = path.join(projectPath, 'src', 'app', 'layout.tsx');
    const layoutContent = "import './globals.css';\n\n" +
      "export default function RootLayout({ children }: { children: React.ReactNode }) {\n" +
      "  return (\n" +
      "    <html lang='en'>\n" +
      "      <body className='antialiased min-h-screen'>\n" +
      "        {children}\n" +
      "      </body>\n" +
      "    </html>\n" +
      "  );\n" +
      "}";
    fs.writeFileSync(layoutPath, layoutContent);
  }

  _generateGlobalsCss(design, projectPath) {
    const cssPath = path.join(projectPath, 'src', 'app', 'globals.css');
    const cssContent = "@import \"tailwindcss\";\n" +
      "\n@theme {\n" +
      "  --color-primary: var(--primary-color);\n" +
      "  --color-secondary: var(--secondary-color);\n" +
      "}\n";
    fs.writeFileSync(cssPath, cssContent);
  }
}

module.exports = new ScaffolderEngine();
